			{ "version" : "/<!-- Generated by coWiki ([^ ]+) \((http:\/\/www.develnet.org|http:\/\/www.cowiki.org)\) -->/ }
			{ "version" : "/<meta name="generator" content="coWiki ([^,]+)", "(http:\/\/www.develnet.org|http:\/\/www.cowiki.org)"[^>]*>/ }
