import sys
import os
			
class cowiki_plugin:
    def get_rules(self):
        return(self.rules)
    def __init__(self):
        self.rules = 
        [
			{ "version" : '/<!-- Generated by coWiki ([^ ]+) \((http:\/\/www.develnet.org|http:\/\/www.cowiki.org)\) -->/ }
			{ "version" : '/<meta name="generator" content="coWiki ([^,]+)", "(http:\/\/www.develnet.org|http:\/\/www.cowiki.org)"[^>]*>/ }
	]

