import sys
import os
			
class hiki_plugin:
    def get_rules(self):
        return(self.rules)
    def __init__(self):
        self.rules = 
        [
			{ "version" : '/<meta name="generator" content="Hiki ([^"^\s]+)">/ }
			{ "text" : '<html><head><title>Hiki Error</title></head><body>' }
			{ "version" : '/<div class="footer">Generated by <a href="http:\/\/hikiwiki.org\/">Hiki<\/a> ([^\s]+) \([\d]{4}-[\d]{2}-[\d]{2}\)/ }
	]

