import sys
import os
			
class modlogan_plugin:
    def get_rules(self):
        return(self.rules)
    def __init__(self):
        self.rules = 
        [
			{ "text" : "<link rel="stylesheet" href="modlogan.css" type="text/css" />" },
			{ "text" : "<LINK REL=STYLESHEET HREF="modlogan.css" type="text/css"></HEAD>" },
			{ "version" : "/Output generated by <a href="http:\/\/www\.(modlogan\.org|kneschke\.de\/projekte\/modlogan\/)">modlogan ([^\s^<]+)<\/a>/", "offset" : "1 },
		]

