import sys
import os
			
class searchfit_shopping_cart_plugin:
    def get_rules(self):
        return(self.rules)
    def __init__(self):
        self.rules = 
        [
			{ "text" : 'This Website is generated by SearchFit Shopping Cart"},
			{ "text" : '<a class="footer_link_system" target="_blank" style="font-size: 10px;" href="http://www.searchfit.com/'},
			{ "text" : 'new SearchFitAnalytics("'},
		]

