import plugins


class Pluginplesk_plugin(plugins.Base):
    def __init__(self):
    	pass

    def start(self):
        self.rules = [
			{"url": "favicon.ico", "md5": "2cee5e3ce2f5c4640a68fc208c286494"},
			{"search": "headers[x-powered-by]", "string": / Plesk([WL] in )/" },
			{ "certainty" : "75", "search" : "headers[server]", "regexp" : "/sw-cp-server/" },
			{ "name" : "logo gif", "regexp" : "/<img src='def_plesk_logo\.gif' alt="Plesk logo"/" },
			{ "text" : "<p>For more information please contact <!--@adminemail@-->" },
			{ "text" : "<div class="poweredBy"><a target="_blank" href="http://www.swsoft.com/en/products/plesk/'},
			{ "text" : "<title>Default PLESK Page</title>" },
			{ "text" : "<title>Default Parallels Plesk Panel Page</title>" },
			{ "text" : "<h1>This is the Plesk&#153; default page</h1>" },
			{ "name" : "copyright parallels", "certainty" : "25", "regexp" : "/&copy; Copyright [\d]{4}\-[\d]{4}", "Parallels</" },
			{ "regexp" : "/This page (was|is) generated by <a href="http:\/\/www\.parallels\.com\/(en\/products\/)?plesk\/">Parallels Plesk Panel<\/a>/" },
			{ "text" : "This page is autogenerated by <a target="_blank" href="http://www.swsoft.com/en/products/plesk/">Plesk'},
			{ "certainty" : "25", "text" : "if (window.plesk_promo.virtuozzo) {" },
			{ "url" : "/", "text" : "</html><!--______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________IE error page size limitation______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________-->" },
			{ "url" : "/", "version" : "/<script language="javascript" type="text\/javascript" src="\/javascript\/common\.js\?plesk_version=psa-([^\s^"]+)"\/?>/" },
		]
	return(self.rules)
